### ISSUE TITLE
Handle nested blocks

### ISSUE THREAD

**Issue by pumbas600** [pumbas600/notion-word-count#2]
Currently, the design uses the fact that all children of the `notion-page-content` class are blocks in order to locate them on the page. They can then have their class extracted from each of these elements to identify the specific type of block. 

This allows for the potential to filter out specific blocks. The issue, however, is that when blocks are indented they become children of the non-indented block above it. This means it's possible to have a text block which contains a code block indented within it. Currently, there is no method of detecting the type of this nested block. 

As a result, if you have excluded code blocks, then they would still get counted if they get indented. Currently, only equations are excluded and as they don't utilise the `data-content-editable-leaf="true"` attribute this doesn't actually have any impact, but if other blocks were to be excluded this would need to be addressed.

To make matters more difficult, it seems like nested blocks are structured differently depending on the containing block, for example, a code block nested within a text block has a different dom structure than a code block nested within a list (Because of the bullet point)

**Comment by JamesNZL** [comment]
> As a result, if you have excluded code blocks, then they would still get counted if they get indented.

Is this because the child element doesn't have a class identifying its type, or because the child element doesn't have the selection class directly?

**Comment by pumbas600** [comment]
> Is this because the child element doesn't have a class identifying its type, or because the child element doesn't have the selection class directly?

The class does exist, it's just that currently there is no logic to go through the DOM of the parent element and determine what is content for itself and what is actually nested blocks (They all just get counted as content of the parent)

**Comment by JamesNZL** [comment]
> > Is this because the child element doesn't have a class identifying its type, or because the child element doesn't have the selection class directly?
> 
> The class does exist, it's just that currently there is no logic to go through the DOM of the parent element and determine what is content for itself and what is actually nested blocks (They all just get counted as content of the parent)

Ahh, so just an implementation restriction, rather than necessarily a technical restriction?

Was just thinking that it *should* be possible to traverse through the tree and filter things out, it'd just be :sparkles: time in-efficient :sparkles: and a pain to implement :smiley:

**Comment by pumbas600** [comment]
> Ahh, so just an implementation restriction, rather than necessarily a technical restriction?

Yeah, it's definitely possible. Unfortunately, I'm already having nightmares about having to recursively try and find blocks within blocks, particularly, having to track block-specific DOM structures so that they can be correctly found even if they're indented within a list or not (Hopefully other blocks don't also lay things out strangely 🙃)

**Comment by JamesNZL** [comment]
The joys of software development 😛
